FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 10001

# Use Gunicorn to run your Flask application dynamically on Render's assigned port
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:10001"]