services:
  db:
    image: mysql:8.0
    command: --default-time-zone='-03:00'
    env_file:
      - ./backend/.env
    ports:
      - "3307:3306"
    volumes:
      - ./backend/db/01_init_db.sql:/docker-entrypoint-initdb.d/01_init_db.sql
      - ./backend/db/02_insert_datos.sql:/docker-entrypoint-initdb.d/02_insert_datos.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -p$$MYSQL_ROOT_PASSWORD -e 'USE restaurante;'"]
      timeout: 5s
      retries: 5
      start_period: 30s
      interval: 5s

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
        db:
          condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:5001"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  db_data: