services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/ca.pem:/app/ca.pem:ro  # Injects the untracked file directly into Docker
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:5001"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend